export { default as Loader} from './Loader'
export { default as Navbar} from './Navbar'
export { default as Footer} from './Footer'
export { default as Header} from './Header'
export { default as Teamsection} from './Teamsection'
export { default as Welcome} from './Welcome'
export { default as Login} from './Login'
// export { default as Register} from './Register'
