export { default as Loader} from './Loader'
export { default as NavBar} from './NavBar'
export { default as Footer} from './Footer'
export { default as Header} from './Header'
export { default as Teamsection} from './Teamsection'
export { default as Welcome} from './Welcome'
export { default as Alanait} from './Alanait'
export { default as Todo} from './Todo'

// export { default as Register} from './Register'
// export { default as Alanaite} from './Alanaite'